- name: template the configuration locally
  connection: local
  template:
    src: bgp.j2
    dest: "{{playbook_dir}}/rendered_configs/{{inventory_hostname}}-bgp.txt"

# - name: push config to device
#   connection: netconf
#   netconf_config:
#     content: "{{ lookup('template', 'bgp.j2') }}"
#     format: text
# NOTE FROM SEAN: needs some more work... this option to send non-xml is only available from junos_config, thread on email internal

- name: push config to device
  connection: netconf
  junos_config:
    src: bgp.j2

- name: grab bgp status
  connection: netconf
  junos_command:
    commands: show bgp summary | display json
  register: output

- name: Print BGP Status
  debug:
    msg: 'BGP STATUS FOR {{peer}} IS {{status}}'
  vars:
    peer: '{{(output.stdout|first)["bgp-information"][0]["bgp-peer"][0]["peer-address"][0]["data"]}}'
    status: '{{(output.stdout|first)["bgp-information"][0]["bgp-peer"][0]["peer-state"][0]["data"]}}'

  - name: set facts
    set_fact:
      peer: '{{(output.stdout|first)["bgp-information"][0]["bgp-peer"][0]["peer-address"][0]["data"]}}'
      status: '{{(output.stdout|first)["bgp-information"][0]["bgp-peer"][0]["peer-state"][0]["data"]}}'
