- name: template the configuration locally
  connection: local
  template:
    src: bgp.j2
    dest: "{{playbook_dir}}/rendered_configs/{{inventory_hostname}}-bgp.txt"

# - name: push config to device
#   connection: netconf
#   netconf_config:
#     content: "{{ lookup('template', 'bgp.j2') }}"
#     format: text

- name: push config to device
  connection: netconf
  junos_config:
    src: bgp.j2

- name: push config to device
  connection: netconf
  junos_command:
    commands: show bgp summary | display json
  register: output

- name: Print BGP Status In JSON
  debug:
    var: output["msg"]
